// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xbyazuwuvwcggteiuvtq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhieWF6dXd1dndjZ2d0ZWl1dnRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3NzE3NjIsImV4cCI6MjA2NjM0Nzc2Mn0.xEhj5xnZgCecSaU_GV4TrNy0jJrmPsraN0wPXPWTS1w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);